### PR TITLE
Fix race when overwriting file with non-empty dir

### LINKED ISSUE #13: Flaky test `whenNonEmptyDirectoryOnSourceAndFileOnDestination_overwritesFileOnDestination`
Caused by race... 2nd worker tries delete after first worker copied...

### PR DESCRIPTION
**Pull request by will-molloy**
Fix #13; the problem was that when you have a non-empty directory replacing a file, it needs to delete the file first. But if there are multiple workers copying, one may delete the directory/files created by another worker:
- `[1]: put(A/B/C/D/E/F.txt)-delete(A/B/C)-createDirs(A/B/C/D/E)-copy(A/B/C/D/E/F.txt)`
- `[2]: put(A/B/C/X/Y/Z.pdf)---------------------------------------------delete(A/B/C)`

Fixed by changing the logic a bit:
- Now do deletes first, so we don't run into these scenarios; it additionally performs delete if there's a file on source and dir on dest, or vice versa
- NOTE this was only a problem for `LocalBackup`, not `S3Backup` since s3 doesn't have the problem of file/dir names matching (folders always end with `/`); so pushed the 'needs deleting' logic into `abstract` method so it can be specialised

Also some refactor:
- Changed `TrieBasedFileTree` to a single `FileTreeNode` class; simpler and less objects created
- Merged `Backup` and `BackupRunner` into an abstract class; it just seems like a better fit, the interface was starting to expose too much, and it's strange having `thenCallRealMethod` so the default methods are used
  - That said, it's also strange testing an abstract class.... I just can't think of a better design atm

### CODE REVIEW

File: file-backup-core/src/main/java/com/willmolloy/backup/File.java [hunk 1]
```diff
@@ -32,6 +32,8 @@ public interface File {
    * @apiNote Used to determine if a file requires updating.
    * @implNote The default implementation just looks at file size.
    */
+  // TODO move this into Backup interface 'needUpdate'?
+  //  Then more control over what is source/dest file
```
Comment (will-molloy) [inline file-backup-core/src/main/java/com/willmolloy/backup/File.java]: .
